name: Deploy Web
on:
  push:
    branches: ["main"]  

jobs:
  build-deploy:
    name: Build Web App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.10.6'
          channel: 'stable'

      - name: Get flutter depedencies
        shell: bash
        run: flutter pub get

      - name: Build flutter web
        shell: bash
        run: flutter build web --release --verbose

      - name: Copy build files
        shell: bash
        run: |
          cp -avr build/web/* docs/
          cp -avr docs/index.html docs/404.html
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
